name: GCP-Release 
on: 
  push:
    tags:
    - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'npm install'
      run: |
          npm install
    - name: 'Make the Distribution Directory'
      run: |
          npm run setup
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/gcp.zip"
        token: ${{ secrets.GCP_DEPLOY }}
